upbit:
  api:
    url: https://api.upbit.com
    value: upbit-api

spring:
  config:
    import: upbit-key.yml

spring.cloud.openfeign:
  client:
    config:
      example-api:
        connectTimeout: 2100
        readTimeout: 5000
        loggerLevel: full
  compression:
    response:
      enabled: false
  httpclient:
    max-connections: 2000
    max-connections-per-route: 500
