spring.application.name: coinbot-web
spring.profiles.active: local

spring:
  config:
    import:
      - client-upbit.yml
      - client-kakao.yml
      - monitoring.yml
      - logging.yml
      - db-core.yml

server:
  port: 8081
  tomcat:
    max-connections: 20000
    threads:
      max: 600
      min-spare: 100

---
spring.config.activate.on-profile: local

---
spring.config.activate.on-profile: local-dev

---
spring.config.activate.on-profile: staging

---
spring.config.activate.on-profile: live